[project]
name = "robosuite"
requires-python = ">=3.8.15"
dynamic = ["version", "dependencies", "authors", "readme"]

[build-system]
requires = ["wheel", "setuptools", "setuptools_scm[toml]"]

[tool.setuptools_scm]
write_to = "robosuite/_version.py"

[tool.setuptools.packages.find]
include = ["robosuite"]


[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }
